name: SoftServeTask

on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Make the script file executable
        run: chmod +x script.sh
      - name: Run the script
        run: ./script.sh